apiVersion: ray.io/v1
kind: RayService
metadata:
  name: wikipedia-classifier
spec:
  serviceUnhealthySecondThreshold: 300
  deploymentUnhealthySecondThreshold: 300
  
  serveConfigV2: |
    applications:
      - name: wikipedia_classifier
        import_path: serve_app:deployment
        route_prefix: /
        deployments:
          - name: WikipediaClassifier
            num_replicas: 1
            ray_actor_options:
              num_cpus: 0.5

  rayClusterConfig:
    rayVersion: '2.9.0'
    
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
            - name: ray-head
              image: wikipedia-classifier:latest
              imagePullPolicy: Never
              workingDir: /app
              ports:
                - containerPort: 6379
                  name: gcs
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
              resources:
                limits:
                  cpu: "1"
                  memory: "2Gi"
                requests:
                  cpu: "500m"
                  memory: "1Gi"
    
    workerGroupSpecs:
      - groupName: small-workers
        replicas: 1
        minReplicas: 1
        maxReplicas: 3
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: wikipedia-classifier:latest
                imagePullPolicy: Never
                workingDir: /app
                resources:
                  limits:
                    cpu: "1"
                    memory: "2Gi"
                  requests:
                    cpu: "500m"
                    memory: "1Gi"